<a href="https://colab.research.google.com/github/Siriyakon-Saenpor/229351_Statistical-Learning-for-Data-Science-1/blob/main/copy_of_lab08_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a = torch.tensor(2)
a

tensor(2)

In [ ]:
b = torch.tensor(3)
a * b

tensor(6)

### Convert a tensor to scalar

In [ ]:
c = b.item()
c

3

### Creating 2D tensor

In [ ]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [ ]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
C.device

device(type='cpu')

In [ ]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [ ]:
D.device

device(type='cuda', index=0)

In [ ]:
C + D #บวกกันไม่ได้

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
D.numpy() #D in GPU (no use numpy)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [ ]:
E * 2

array([[ 2,  4],
       [10, 12]])

In [ ]:
E - 2

array([[-1,  0],
       [ 3,  4]])

In [ ]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [ ]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [ ]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [ ]:
A

tensor([[4, 5],
        [8, 9]])

In [ ]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(1, 2, 3) #3D
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
I = torch.eye(3) #3*3
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
R1 = torch.rand(2, 3)
R1

tensor([[0.6163, 0.9190, 0.5686],
        [0.9851, 0.4678, 0.7149]])

In [ ]:
R2 = torch.randn(2, 3)
R2

tensor([[-0.1269,  0.5685, -0.8303],
        [-0.1848,  1.3471, -2.8618]])

In [ ]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [ ]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [ ]:
u

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [ ]:
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
w = u.view(3, 2)
w.shape

torch.Size([3, 2])

In [ ]:
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [ ]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
a

tensor([0, 1, 2, 3])

In [ ]:
b

tensor([1, 2, 3, 4])

In [ ]:
# concatenate
e = torch.cat([a, b], axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [ ]:
f = torch.cat([a, b], axis=1) #ทำไม่ได้
f

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
P[[0, 1, 2], [0, 1, 2]]
P[0:3, 0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [ ]:
torch.inverse(torch.tensor([[2.0, 0.0], [0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
A ** 2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
A.sum()

tensor(0.)

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

In [ ]:
ones = torch.ones(200, 1)

In [ ]:
X = torch.cat([ones, X], axis=1)
X

tensor([[ 1.0000, -2.0269,  0.0800,  ...,  1.4870,  0.6968,  0.3743],
        [ 1.0000,  0.2706,  0.0228,  ..., -0.2917, -0.5624, -0.0431],
        [ 1.0000, -1.4342,  1.1414,  ..., -0.6498,  1.6563, -0.5204],
        ...,
        [ 1.0000, -1.3031, -0.1891,  ..., -0.9556,  0.9482, -1.0617],
        [ 1.0000, -0.1206, -1.2211,  ...,  0.8524,  1.2512, -0.6065],
        [ 1.0000, -1.4047, -2.5824,  ..., -0.7115,  0.0476, -1.0664]])

In [ ]:
y = X @ b + e

In [ ]:
b_hat = torch.inverse(X.t() @ X) @ X.t() @ y

In [ ]:
y_hat = X @ b_hat

In [ ]:
y_np = y.numpy()
y_hat_np = y_hat.numpy()

In [ ]:
mse = np.mean((y_np - y_hat_np) ** 2)
mse

np.float32(0.8684679)